### ISSUE TITLE
Bug: Corriger problème de .env

### ISSUE THREAD

**Issue by MrAnyx** [Buissartt/Laoutira#1]
## Description

Il va falloir retirer le `.env` du repository pour qu'on puisse mettre nos identifiants de bdd chacun de notre coté.

## Tâches

- [ ] Retirer le `.env` du repository en local sur `master`
- [ ] Ajouter le `.env` dans le fichier `.gitignore`
- [ ] **Push** les modifs sur `master`
- [ ] **Pull** les dernières modifs

**Comment by Buissartt** [comment]
Ça sera fait, mais à ce stade il s'agit simplement de l'initialisation du repository.
