### ISSUE TITLE
Bug: Mauvais alignement des éléments de la section "Comment ça marche"

### ISSUE THREAD

**Issue by Buissartt** [Buissartt/Laoutira#10]
## Description du bug
Sur des tailles d'écran réduites, les images de la section comment ça marche ne sont pas centrées comme sur la maquette. De plus, le texte ne prend pas assez de largeur (toujours sur les écrans réduits)

Enfin, sur de grands écrans, il n'y a pas assez de bordures sur les cotés des éléments.

## Screenshots
Mauvais alignement :
![image](https://user-images.githubusercontent.com/45772077/102760240-86660680-4375-11eb-9ce6-981d06429862.png)

Manque de bordure : 
![image](https://user-images.githubusercontent.com/45772077/102760727-42273600-4376-11eb-91c1-99a17d1b91f3.png)

## Pour le reproduire
Réduire la taille de l'écran
## Comportement attendu
Alignement correct :
![image](https://user-images.githubusercontent.com/45772077/102760386-b90fff00-4375-11eb-8e73-33ce761b8aa2.png)

Bordures correctes :
![image](https://user-images.githubusercontent.com/45772077/102760770-52d7ac00-4376-11eb-8550-2055bec766cd.png)

## Plateforme

- [x] Desktop
- [x] Mobile

**Comment by MrAnyx** [comment]
Done !
