### ISSUE TITLE
Feat: Refonte de la zone "Notre questionnaire" de la landing page

### ISSUE THREAD

**Issue by Buissartt** [Buissartt/Laoutira#13]
## Description
Faire une refonte totale de la zone "Notre questionnaire" de la landing page.

## Eléments attendus
Une zone jolie et fonctionnelle avec : 
- Nombre de villes présentes en base de données
- Nombre de fois où le questionnaire a été remplis
- Nombre de personnes ayant déménagé grâce à "Cmaville"

## Liens de dépendances (Issue(s) nécessaire(s) pour la réalisation de celle-ci)
Landing page existante.

## Screenshot (optionnel)
Pas de maquette.

## Tâches
Pas nécessaire.

**Comment by MrAnyx** [comment]
Done !
