### ISSUE TITLE
Feat: Ajouter les tag og pour chaque page

### ISSUE THREAD

**Issue by MrAnyx** [Buissartt/Laoutira#17]
## Description
Il faudrait ajouter les tags `og` pour chaque page en utilisant les block `og` du template `base.html.twig`.

## Eléments attendus
Des tags `og` pour toutes les pages.

## Liens de dépendances (Issue(s) nécessaire(s) pour la réalisation de celle-ci)

- [x] #16 - Ajouter le nouveau logo

## Tâches

- [x] Ajouter les tags `og`
- [x] Vérifer qu'ils sont correctes

**Comment by Buissartt** [comment]
Not tested, but done.
