### ISSUE TITLE
Bug: Stepper include results in quiz page

### ISSUE THREAD

**Issue by Buissartt** [Buissartt/Laoutira#21]
## Description du bug
Le stepper inclus les résultats plutôt que seulement les questions sur la page du quiz.
## Pour le reproduire
Appuyer sur la bouton pour afficher les résultats
## Comportement attendu
Le max du stepper doit être le champ email.
## Plateforme

- [x] Desktop
- [x] Mobile

**Comment by MrAnyx** [comment]
Done !
