### ISSUE TITLE
Bug: Footer map's zoom

### ISSUE THREAD

**Issue by Buissartt** [Buissartt/Laoutira#25]
## Description du bug
Le zoom de la carte dans le footer n'est pas automatique alors qu'il devrait l'être dès l'ouverture sur le point ciblé.
## Screenshots
![image](https://user-images.githubusercontent.com/45772077/104498210-adfa6880-55db-11eb-88c2-c32a685c34ce.png)

## Pour le reproduire
Ouvrir la carte dans le footer en cliquant sur l'icone maps

## Comportement attendu
![image](https://user-images.githubusercontent.com/45772077/104498614-3842cc80-55dc-11eb-819f-a2b028706124.png)

## Plateforme

- [x] Desktop
- [x] Mobile

**Comment by MrAnyx** [comment]
Done !
