### ISSUE TITLE
Bug: Quiz submit button style onclick

### ISSUE THREAD

**Issue by Buissartt** [Buissartt/Laoutira#27]
## Description du bug
Modifier le style du bouton d'envoi du questionnaire quand le clic est maintenu
## Screenshots
![image](https://user-images.githubusercontent.com/45772077/105696180-41e50200-5f03-11eb-8a95-98c180f4b527.png)

## Pour le reproduire
Maintenir le clic appuyé sur le bouton d'envoi du questionnaire

## Comportement attendu
Pas de bordure bleutée

## Plateforme

- [x] Desktop
- [x] Mobile

**Comment by MrAnyx** [comment]
Euh, je ne suis pas sûr d'avoir compris ce que tu demandes 😂

**Comment by Buissartt** [comment]
> Euh, je ne suis pas sûr d'avoir compris ce que tu demandes 😂

Je m'en doutais, ça porte un nom que j'ai oublié. En gros quand tu cliques sur le bouton envoyer et que tu maintiens le clic, bootstrap ajoute un contour gris/bleu au bouton, il faudrait changer ça.

**Comment by Buissartt** [comment]
Solved ! :smile:
