### ISSUE TITLE
Bug: Sortable section not readonly after submission

### ISSUE THREAD

**Issue by Buissartt** [Buissartt/Laoutira#28]
## Description du bug
Once the quiz is submited, ALL the quiz section should be readonly. That's why we should disable the sortable section at the end.

## Pour le reproduire
Submit the quiz, and then order your choices.

## Comportement attendu
Quiz full readonly after submission

## Plateforme

- [x] Desktop
- [x] Mobile

**Comment by MrAnyx** [comment]
Done !
