### ISSUE TITLE
Feat: Créer le template de base

### ISSUE THREAD

**Issue by MrAnyx** [Buissartt/Laoutira#8]
## Description

Créer le template de base pour les pages twig

## Eléments attendus

- Un fichier `base.html.twig`
- Une navbar dans le fichier de base

## Screenshot (optionnel)

![screencapture-laoutira-mystrikingly-2020-12-17-18_41_49](https://user-images.githubusercontent.com/44176707/102530302-6696c000-40a1-11eb-8fe1-f5a59d382be5.png)

## Tâches

- [x] Update le fichier `base.html.twig`
- [x] Ajouter les fichiers CSS / JS
- [x] Ajouter bootstrap
- [x] Mettre en place la navbar
- [x] Mettre en place le footer
- [x] Créer les blocks `body`, `stylesheets`, `js`, `title`, et un pour les tag `og` pour le SEO

**Comment by Buissartt** [comment]
All tasks are finished, closing the issue.
