### ISSUE TITLE
Bug: Modifier les liens pour les boutons vers les réseaux sociaux

### ISSUE THREAD

**Issue by MrAnyx** [Buissartt/Laoutira#9]
## Description du bug

Les liens des boutons `facebook` et `twitter` ne mènent pas vers les bons liens 

## Screenshots

![image](https://user-images.githubusercontent.com/44176707/102664708-a03ff780-4183-11eb-929b-6532f8f95af6.png)

## Pour le reproduire

Pas nécessaire

## Comportement attendu

Les boutons devraient renvoyer vers les bons liens

## Plateforme

- [x] Desktop
- [x] Mobile

**Comment by Buissartt** [comment]
# Éléments nécessaires à la correction :
- [ ] Compte Twitter de Laoutira
- [ ] Lien vers la page Facebook de Laoutira


# Liens d'obtention des boutons :

- https://publish.twitter.com/
- https://developers.facebook.com/docs/plugins/like-button/?locale=fr_FR
